### ISSUE TITLE
invalid SBML

### ISSUE THREAD

**Issue by fbergmann** [dagwa/wholecell-translation#1]
Hello, 

I've had a look at the sbml models you generated, however unfortunately they are invalid. In the reactions you reference species, that are not declared as species in the list of reactions. 

For example in: 

```
<reaction id="MG_001_MONOMER_p268_plus_I1" name="MG_001_MONOMER_p268_plus_I1" reversible="false" fast="false">
    <listOfReactants>
      <speciesReference species="MG_001_MONOMER_p268" constant="false"/>
      <speciesReference species="aminoacylated_MG472" constant="false"/>
      <speciesReference species="GTP" stoichiometry="2" constant="false"/>
      <speciesReference species="MG_089_MONOMER" constant="false"/>
      <speciesReference species="MG_451_MONOMER" constant="false"/>
      <speciesReference species="H2O" stoichiometry="2" constant="false"/>
    </listOfReactants>
    <listOfProducts>
      <speciesReference species="MG_001_MONOMER_p269" constant="false"/>
      <speciesReference species="MG472" constant="false"/>
      <speciesReference species="GDP" stoichiometry="2" constant="true"/>
      <speciesReference species="PI" stoichiometry="2" constant="true"/>
      <speciesReference species="MG_089_MONOMER" constant="true"/>
      <speciesReference species="MG_451_MONOMER" constant="true"/>
      <speciesReference species="H" stoichiometry="2" constant="true"/>
    </listOfProducts>
    <kineticLaw>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <apply>
          <times/>
          <ci> k </ci>
          <ci> GTP </ci>
          <ci> GTP </ci>
          <ci> MG_089_MONOMER </ci>
          <ci> MG_451_MONOMER </ci>
          <ci> MG_001_MONOMER_p268 </ci>
        </apply>
      </math>
    </kineticLaw>
  </reaction>
```

most of the species are not declared in the file. Maybe I looked in the wrong place, i looked under the 'modelGeneration' folder. 

Thanks
Frank

**Comment by den2042** [comment]
Hello Frank
It is now fixed. New species are added. 
Thank you for pointing it out.

Indeed, translation SBML file model_toy.xml is in modelGeneration folder. Of note, it contains the model of translation for three proteins only. The full translation SBML model would be several Gbs  large. So, we decided not to upload it on github. 

Regards
Denis

**Comment by den2042** [comment]
Hello Frank
It is now fixed. New species are added.
Thank you for pointing it out.

Indeed, translation SBML file model_toy.xml is in modelGeneration 
folder. Of note, it contains the model of translation for three proteins 
only. The full translation SBML model would be several Gbs large. So, we 
decided not to upload it on github.

Regards
Denis

**Comment by fbergmann** [comment]
Unfortunately the problem is still there: 

```
>EXCEPTION 2015-08-05 23:09:13<
  Error while importing reaction "MG_001_MONOMER_Transl_Init".
    CReaction (7): Species object 'MG_143_MONOMER' is neither substrate, 
    product nor modifier to reaction 'MG_001_MONOMER_Transl_Init' but it is 
    used in the kinetic law.
```

you could easily try to validate the file if you like. we could add a step to your script in which you could call libSBML validation (using the libsbml python bindings [1](http://sbml.org/Software/libSBML/5.11.4/docs/formatted/python-api/validate_s_b_m_l_8py-example.html)), or you could simply zip the xml file and upload it to: 

```
  http://sbml.org/validator/
```

and it would tell you what is wrong.

**Comment by jcursons** [comment]
Hi Frank,

The problem may have arisen due to the script changes when generating the toy model. I know that I could load a previous toy version into COPASI and run it, which means that all of the species etc had to be defined in that version.

The web validation tool looks useful, but as Denis said the full translation XML file is several GB - simply loading the model into COPASI takes several hours - and so I don't think you want us smashing the server's bandwidth with testing successive versions?

Once someone has responded to Denis's question which he sent out overnight (to the full mailing list), we will decide which approach to take and re-write the translation model in a more computationally tractable form. Perhaps it's best if you save your time/effort for working on that version?

Thanks,
Joe

**Comment by fbergmann** [comment]
no problem at all,and I agree the online service is not meant for gigabytes of files. However, running a local validation would probably make sense, once you are getting to your final solution. In any case there is no rush.
